/**
 */
const setting = {
    publicPath: '/',
    outputDir: 'dist',
    assetsDir: '',
    lintOnSave: true,
    transpileDependencies: ['vue-echarts', 'resize-detector'],
    baseURL: '',
    title: 'H2O',
    titleSeparator: ' - ',
    titleReverse: false,
    abbreviation: 'vab-pro',
    devPort: '9995',
    version: process.env.VUE_APP_VERSION,
    copyright: '© COPYRIGHT H2O',
    keepAliveMaxNum: 99,
    routerMode: 'hash',
    routesVarifyList: [],
    routesWhiteList: [],
    loadingText: 'Loading...',
    tokenName: 'token',
    storage: 'localstorage',
    recordRoute: true,
    logo: 'vuejs-fill',
    i18n: 'en',
    errorLog: ['development', 'production'],
    loginInterception: true,
    loginRSA: false,
    authentication: 'intelligence',
    rolesControl: false,
    uniqueOpened: false,
    defaultOpeneds: ['/launchpad'],
    debounce: ['doEdit'],
    providePlugin: {},
    build7z: false,
    templateFolder: 'project',
    donation: false,
    openFirstMenu: true
}
module.exports = setting
